name: Compile Sketch for ESP32
on:
  - push
  - pull_request
jobs:        
  compile_sketch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Rename config file 
        run: mv esp-smartmeter-reader/config_esp32.h esp-smartmeter-reader/config.h
      - uses: arduino/compile-sketches@v1.1.0
        with:
          fqbn: 'esp32:esp32:esp32'
          sketch-paths: |
            - esp-smartmeter-reader
          platforms: |
            - name: esp32:esp32
              source-url: https://dl.espressif.com/dl/package_esp32_index.json
          libraries: |
            - name: FastCRC
            - name: ArduinoJson
            - name: PubSubClient