name: Compile Sketch for ESP8266
on:
  - push
  - pull_request
jobs:        
  compile_sketch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Rename config file 
        run: mv esp-smartmeter-reader/config_esp8266.h esp-smartmeter-reader/config.h
      - uses: arduino/compile-sketches@v1.1.0
        with:
          fqbn: 'esp8266:esp8266:generic'
          sketch-paths: |
            - esp-smartmeter-reader
          platforms: |
            - name: esp8266:esp8266
              source-url: http://arduino.esp8266.com/stable/package_esp8266com_index.json
          libraries: |
            - name: FastCRC
            - name: ArduinoJson
            - name: PubSubClient
            - name: Crypto